### ISSUE TITLE
I'm not sure how to install this.

### ISSUE THREAD

**Issue by NaturalHarmonia** [mcred/crissaegrim#1]
Could anyone help?

**Comment by mcred** [comment]
You can download a precompiled version from [here](https://mcred.io/downloads/). It's only been compiled for OSX.

**Comment by NaturalHarmonia** [comment]
I guess I'm out of luck. I use Windows.

**Comment by mcred** [comment]
You should be able to clone the project and build it with `npm run electron` after you install the dependencies. I haven't used electron on windows, though, so I don't know if you'll have any issues.

**Comment by mcred** [comment]
Closing this as the NPM version is archived and a newer Kotlin version is coming soon.
